#!/usr/bin/env node

var sys = require('sys')
var exec = require('child_process').exec;

var args = process.argv.slice(2);

if (args.length == 0) {
	console.log("\nCommands:\n    build,\n    rebuild,\n    clean,\n    run,\n    run-without-web-server\n");
	process.exit(0);
}

function build () {
		console.log("    Building...");
        function puts(error, stdout, stderr) {
                sys.puts(stdout);
				if (error) {
					console.error(error);
				}
				else {
					console.log("    Success!");
				}
        }
        exec("./buildlib.sh", puts);
}

function run () {
	console.log("    Running.");
    exec("./build.sh", function (error, stdout, stderr) {
            sys.puts(stdout);
	});
}

function runWebSever () {
	console.log("    Starting SimpleHTTPServer");
    exec("python -m SimpleHTTPServer", function (error, stdout, stderr) {
            sys.puts(stdout);
	});
}

function clean () {

        function puts(error, stdout, stderr) {

        }
		console.log("    Removing libs.js");
        exec("rm libs.js", puts);
		console.log("    Removing pw.js");
		exec("rm pw.js", puts);
}


if (args[0] == "rebuild") {
	clean();
	build();
}
if (args[0] == "build") {
	build();
}

if (args[0] == "clean") {
	clean();
}

if (args[0] == "run") {
	run();
	runWebSever();
	console.log("    To terminate this proccess ctrl-c it.");
}

if (args[0] == "run-without-web-server") {
	run();
	console.log("    To terminate this proccess ctrl-c it.");
}